import type { EmployeeInput } from "./types";

// NKPL's June 2026 payroll roster, sourced from the company's own June
// payroll sheet (jun.csv). salaryPerDay comes directly from that sheet's
// "SALARY DAY/MONTH" column; daysWorked/extraDays reflect June's actual
// recorded attendance. Employee ids are reused from sampleEmployees.ts for
// anyone who also appears there, so salary/day + bonus/day rates edited in
// either month stay in sync via the shared per-employee rate store.
export const juneEmployees: EmployeeInput[] = [
  {
    "id": "emp-1",
    "name": "GURU PRASAD PATRA",
    "category": "Skilled",
    "monthlySalary": 26200,
    "salaryPerDay": 650,
    "bonusPerDay": 223,
    "daysWorked": 30,
    "extraDays": 0,
    "basicPercent": 70,
    "pfOptIn": false,
    "esiOptIn": false,
    "advance": null,
    "otherDeduction": 0
  },
  {
    "id": "emp-2",
    "name": "Samir Dey",
    "category": "Semi-skilled",
    "monthlySalary": 13500,
    "salaryPerDay": 367,
    "bonusPerDay": 83,
    "daysWorked": 27,
    "extraDays": 0,
    "basicPercent": 70,
    "pfOptIn": true,
    "esiOptIn": true,
    "advance": null,
    "otherDeduction": 0
  },
  {
    "id": "emp-3",
    "name": "SISIR HEMRAM",
    "category": "Semi-skilled",
    "monthlySalary": 16950,
    "salaryPerDay": 400,
    "bonusPerDay": 165,
    "daysWorked": 30,
    "extraDays": 0,
    "basicPercent": 70,
    "pfOptIn": true,
    "esiOptIn": true,
    "advance": null,
    "otherDeduction": 0
  },
  {
    "id": "emp-4",
    "name": "S K SAJAMAL",
    "category": "Skilled",
    "monthlySalary": 22700,
    "salaryPerDay": 567,
    "bonusPerDay": 190,
    "daysWorked": 27,
    "extraDays": 0,
    "basicPercent": 70,
    "pfOptIn": false,
    "esiOptIn": false,
    "advance": null,
    "otherDeduction": 0
  },
  {
    "id": "emp-5",
    "name": "Tapas Chandra Kumar",
    "category": "Semi-skilled",
    "monthlySalary": 14500,
    "salaryPerDay": 340,
    "bonusPerDay": 143,
    "daysWorked": 30,
    "extraDays": 0,
    "basicPercent": 70,
    "pfOptIn": true,
    "esiOptIn": true,
    "advance": null,
    "otherDeduction": 0
  },
  {
    "id": "emp-j1",
    "name": "UTTAM DAS",
    "category": "Skilled",
    "monthlySalary": 27000,
    "salaryPerDay": 500,
    "bonusPerDay": 400,
    "daysWorked": 16,
    "extraDays": 0,
    "basicPercent": 70,
    "pfOptIn": true,
    "esiOptIn": false,
    "advance": null,
    "otherDeduction": 0
  },
  {
    "id": "emp-7",
    "name": "Anupam Mahesh",
    "category": "Skilled",
    "monthlySalary": 32000,
    "salaryPerDay": 933,
    "bonusPerDay": 133,
    "daysWorked": 30,
    "extraDays": 0,
    "basicPercent": 70,
    "pfOptIn": false,
    "esiOptIn": false,
    "advance": null,
    "otherDeduction": 0
  },
  {
    "id": "emp-8",
    "name": "SAUMYA ROY",
    "category": "Semi-skilled",
    "monthlySalary": 15000,
    "salaryPerDay": 367,
    "bonusPerDay": 150,
    "daysWorked": 18,
    "extraDays": 0,
    "basicPercent": 70,
    "pfOptIn": true,
    "esiOptIn": true,
    "advance": null,
    "otherDeduction": 0
  },
  {
    "id": "emp-j2",
    "name": "PRIYOJIT GHOSH",
    "category": "Skilled",
    "monthlySalary": 22500,
    "salaryPerDay": 557,
    "bonusPerDay": 193,
    "daysWorked": 0,
    "extraDays": 0,
    "basicPercent": 70,
    "pfOptIn": false,
    "esiOptIn": false,
    "advance": null,
    "otherDeduction": 0
  },
  {
    "id": "emp-10",
    "name": "Ashok Ram",
    "category": "Semi-skilled",
    "monthlySalary": 19000,
    "salaryPerDay": 523,
    "bonusPerDay": 110,
    "daysWorked": 30,
    "extraDays": 1,
    "basicPercent": 70,
    "pfOptIn": true,
    "esiOptIn": true,
    "advance": 1500,
    "otherDeduction": 0
  },
  {
    "id": "emp-11",
    "name": "Kajal Senapati",
    "category": "Unskilled",
    "monthlySalary": 7000,
    "salaryPerDay": 200,
    "bonusPerDay": 33,
    "daysWorked": 29,
    "extraDays": 0,
    "basicPercent": 70,
    "pfOptIn": true,
    "esiOptIn": true,
    "advance": 500,
    "otherDeduction": 0
  },
  {
    "id": "emp-12",
    "name": "Sushanta Ghosh",
    "category": "Unskilled",
    "monthlySalary": 9600,
    "salaryPerDay": 320,
    "bonusPerDay": 35,
    "daysWorked": 27,
    "extraDays": 0,
    "basicPercent": 70,
    "pfOptIn": true,
    "esiOptIn": true,
    "advance": null,
    "otherDeduction": 0
  },
  {
    "id": "emp-13",
    "name": "Keya Patra",
    "category": "Unskilled",
    "monthlySalary": 6800,
    "salaryPerDay": 217,
    "bonusPerDay": 10,
    "daysWorked": 28,
    "extraDays": 0,
    "basicPercent": 70,
    "pfOptIn": true,
    "esiOptIn": true,
    "advance": null,
    "otherDeduction": 0
  },
  {
    "id": "emp-14",
    "name": "Bulti Ghosh",
    "category": "Unskilled",
    "monthlySalary": 9600,
    "salaryPerDay": 320,
    "bonusPerDay": 15,
    "daysWorked": 29,
    "extraDays": 0,
    "basicPercent": 70,
    "pfOptIn": true,
    "esiOptIn": true,
    "advance": null,
    "otherDeduction": 0
  },
  {
    "id": "emp-15",
    "name": "Mira Prasad",
    "category": "Unskilled",
    "monthlySalary": 9600,
    "salaryPerDay": 320,
    "bonusPerDay": 15,
    "daysWorked": 11,
    "extraDays": 0,
    "basicPercent": 70,
    "pfOptIn": true,
    "esiOptIn": true,
    "advance": null,
    "otherDeduction": 0
  },
  {
    "id": "emp-16",
    "name": "Karabi Chakraborty",
    "category": "Unskilled",
    "monthlySalary": 9600,
    "salaryPerDay": 320,
    "bonusPerDay": 15,
    "daysWorked": 16,
    "extraDays": 0,
    "basicPercent": 70,
    "pfOptIn": true,
    "esiOptIn": true,
    "advance": null,
    "otherDeduction": 0
  },
  {
    "id": "emp-17",
    "name": "Tarapada Ghosh",
    "category": "Unskilled",
    "monthlySalary": 9600,
    "salaryPerDay": 320,
    "bonusPerDay": 65,
    "daysWorked": 27,
    "extraDays": 0,
    "basicPercent": 70,
    "pfOptIn": true,
    "esiOptIn": true,
    "advance": null,
    "otherDeduction": 0
  },
  {
    "id": "emp-18",
    "name": "Pratima Digar",
    "category": "Unskilled",
    "monthlySalary": 9600,
    "salaryPerDay": 320,
    "bonusPerDay": 15,
    "daysWorked": 26,
    "extraDays": 0,
    "basicPercent": 70,
    "pfOptIn": true,
    "esiOptIn": true,
    "advance": null,
    "otherDeduction": 0
  },
  {
    "id": "emp-19",
    "name": "Parimal Ghosh(Security)",
    "category": "Unskilled",
    "isSecurity": true,
    "monthlySalary": 6600,
    "salaryPerDay": 220,
    "bonusPerDay": 10,
    "daysWorked": 27,
    "extraDays": 0,
    "basicPercent": 70,
    "pfOptIn": true,
    "esiOptIn": true,
    "advance": null,
    "otherDeduction": 0
  },
  {
    "id": "emp-20",
    "name": "Monaj Chatterjee(Security)",
    "category": "Unskilled",
    "isSecurity": true,
    "monthlySalary": 6600,
    "salaryPerDay": 220,
    "bonusPerDay": 10,
    "daysWorked": 29,
    "extraDays": 0,
    "basicPercent": 70,
    "pfOptIn": true,
    "esiOptIn": true,
    "advance": null,
    "otherDeduction": 0
  },
  {
    "id": "emp-21",
    "name": "Sunil Sahani",
    "category": "Unskilled",
    "monthlySalary": 10050,
    "salaryPerDay": 335,
    "bonusPerDay": 65,
    "daysWorked": 16,
    "extraDays": 0,
    "basicPercent": 70,
    "pfOptIn": true,
    "esiOptIn": true,
    "advance": null,
    "otherDeduction": 0
  },
  {
    "id": "emp-22",
    "name": "SOMNATH MONDAL",
    "category": "Unskilled",
    "monthlySalary": 10050,
    "salaryPerDay": 335,
    "bonusPerDay": 65,
    "daysWorked": 28,
    "extraDays": 0,
    "basicPercent": 70,
    "pfOptIn": true,
    "esiOptIn": true,
    "advance": null,
    "otherDeduction": 0
  },
  {
    "id": "emp-23",
    "name": "SUROJIT KOLEY",
    "category": "Unskilled",
    "monthlySalary": 10050,
    "salaryPerDay": 335,
    "bonusPerDay": 50,
    "daysWorked": 26,
    "extraDays": 0,
    "basicPercent": 70,
    "pfOptIn": true,
    "esiOptIn": true,
    "advance": null,
    "otherDeduction": 0
  },
  {
    "id": "emp-24",
    "name": "Abhijit Majhi",
    "category": "Unskilled",
    "monthlySalary": 9750,
    "salaryPerDay": 325,
    "bonusPerDay": 75,
    "daysWorked": 29,
    "extraDays": 0,
    "basicPercent": 70,
    "pfOptIn": true,
    "esiOptIn": true,
    "advance": null,
    "otherDeduction": 0
  },
  {
    "id": "emp-25",
    "name": "Samir Santra",
    "category": "Unskilled",
    "monthlySalary": 10050,
    "salaryPerDay": 335,
    "bonusPerDay": 65,
    "daysWorked": 29,
    "extraDays": 0,
    "basicPercent": 70,
    "pfOptIn": true,
    "esiOptIn": true,
    "advance": null,
    "otherDeduction": 0
  },
  {
    "id": "emp-26",
    "name": "Biswajit Paul",
    "category": "Unskilled",
    "monthlySalary": 9750,
    "salaryPerDay": 325,
    "bonusPerDay": 75,
    "daysWorked": 27,
    "extraDays": 0,
    "basicPercent": 70,
    "pfOptIn": true,
    "esiOptIn": true,
    "advance": null,
    "otherDeduction": 0
  },
  {
    "id": "emp-27",
    "name": "Monojit Pal",
    "category": "Unskilled",
    "monthlySalary": 9750,
    "salaryPerDay": 325,
    "bonusPerDay": 75,
    "daysWorked": 30,
    "extraDays": 1,
    "basicPercent": 70,
    "pfOptIn": true,
    "esiOptIn": true,
    "advance": null,
    "otherDeduction": 0
  },
  {
    "id": "emp-28",
    "name": "Jayanta Koley",
    "category": "Unskilled",
    "monthlySalary": 10050,
    "salaryPerDay": 335,
    "bonusPerDay": 65,
    "daysWorked": 24,
    "extraDays": 0,
    "basicPercent": 70,
    "pfOptIn": true,
    "esiOptIn": true,
    "advance": 2000,
    "otherDeduction": 0
  },
  {
    "id": "emp-29",
    "name": "Subhendu Pal",
    "category": "Unskilled",
    "monthlySalary": 9750,
    "salaryPerDay": 325,
    "bonusPerDay": 75,
    "daysWorked": 30,
    "extraDays": 0,
    "basicPercent": 70,
    "pfOptIn": true,
    "esiOptIn": true,
    "advance": null,
    "otherDeduction": 0
  },
  {
    "id": "emp-30",
    "name": "Tanmoy Dastanti",
    "category": "Unskilled",
    "monthlySalary": 9750,
    "salaryPerDay": 325,
    "bonusPerDay": 75,
    "daysWorked": 27,
    "extraDays": 0,
    "basicPercent": 70,
    "pfOptIn": true,
    "esiOptIn": true,
    "advance": null,
    "otherDeduction": 0
  },
  {
    "id": "emp-31",
    "name": "Baleswar Saha",
    "category": "Unskilled",
    "monthlySalary": 9750,
    "salaryPerDay": 325,
    "bonusPerDay": 75,
    "daysWorked": 26,
    "extraDays": 0,
    "basicPercent": 70,
    "pfOptIn": true,
    "esiOptIn": true,
    "advance": null,
    "otherDeduction": 0
  },
  {
    "id": "emp-32",
    "name": "Sanjay Das",
    "category": "Unskilled",
    "monthlySalary": 10050,
    "salaryPerDay": 335,
    "bonusPerDay": 65,
    "daysWorked": 29,
    "extraDays": 0,
    "basicPercent": 70,
    "pfOptIn": true,
    "esiOptIn": true,
    "advance": null,
    "otherDeduction": 0
  },
  {
    "id": "emp-33",
    "name": "Asish Dastanti",
    "category": "Unskilled",
    "monthlySalary": 10050,
    "salaryPerDay": 335,
    "bonusPerDay": 65,
    "daysWorked": 30,
    "extraDays": 0,
    "basicPercent": 70,
    "pfOptIn": true,
    "esiOptIn": true,
    "advance": null,
    "otherDeduction": 0
  },
  {
    "id": "emp-34",
    "name": "Saikat Ghosh",
    "category": "Unskilled",
    "monthlySalary": 9750,
    "salaryPerDay": 325,
    "bonusPerDay": 75,
    "daysWorked": 27,
    "extraDays": 0,
    "basicPercent": 70,
    "pfOptIn": true,
    "esiOptIn": true,
    "advance": null,
    "otherDeduction": 0
  },
  {
    "id": "emp-35",
    "name": "Kamal krishna saha",
    "category": "Unskilled",
    "monthlySalary": 9450,
    "salaryPerDay": 315,
    "bonusPerDay": 85,
    "daysWorked": 29,
    "extraDays": 0,
    "basicPercent": 70,
    "pfOptIn": true,
    "esiOptIn": true,
    "advance": null,
    "otherDeduction": 0
  },
  {
    "id": "emp-36",
    "name": "Bimal hazra",
    "category": "Unskilled",
    "monthlySalary": 9450,
    "salaryPerDay": 315,
    "bonusPerDay": 85,
    "daysWorked": 24,
    "extraDays": 0,
    "basicPercent": 70,
    "pfOptIn": true,
    "esiOptIn": true,
    "advance": null,
    "otherDeduction": 0
  },
  {
    "id": "emp-37",
    "name": "Sonal Goenka",
    "category": "Special",
    "monthlySalary": 60000,
    "salaryPerDay": 2000,
    "bonusPerDay": 0,
    "daysWorked": 30,
    "extraDays": 0,
    "basicPercent": 70,
    "pfOptIn": false,
    "esiOptIn": false,
    "advance": null,
    "otherDeduction": 0
  },
  {
    "id": "emp-38",
    "name": "Rahul Somani",
    "category": "Special",
    "monthlySalary": 25000,
    "salaryPerDay": 833,
    "bonusPerDay": 0,
    "daysWorked": 30,
    "extraDays": 0,
    "basicPercent": 70,
    "pfOptIn": false,
    "esiOptIn": false,
    "advance": null,
    "otherDeduction": 0
  },
  {
    "id": "emp-39",
    "name": "Anjali Sodhani",
    "category": "Special",
    "monthlySalary": 25000,
    "salaryPerDay": 833,
    "bonusPerDay": 0,
    "daysWorked": 30,
    "extraDays": 0,
    "basicPercent": 70,
    "pfOptIn": false,
    "esiOptIn": false,
    "advance": null,
    "otherDeduction": 0
  },
  {
    "id": "emp-40",
    "name": "Rishi Jhajharia",
    "category": "Special",
    "monthlySalary": 25000,
    "salaryPerDay": 833,
    "bonusPerDay": 0,
    "daysWorked": 30,
    "extraDays": 0,
    "basicPercent": 70,
    "pfOptIn": false,
    "esiOptIn": false,
    "advance": null,
    "otherDeduction": 0
  },
  {
    "id": "emp-41",
    "name": "Avijit Mondal",
    "category": "Skilled",
    "monthlySalary": 35000,
    "salaryPerDay": 1167,
    "bonusPerDay": 0,
    "daysWorked": 6,
    "extraDays": 0,
    "basicPercent": 70,
    "pfOptIn": false,
    "esiOptIn": false,
    "advance": null,
    "otherDeduction": 0
  },
  {
    "id": "emp-42",
    "name": "Bindu Chirania",
    "category": "Special",
    "monthlySalary": 60000,
    "salaryPerDay": 2000,
    "bonusPerDay": 0,
    "daysWorked": 30,
    "extraDays": 0,
    "basicPercent": 70,
    "pfOptIn": false,
    "esiOptIn": false,
    "advance": null,
    "otherDeduction": 0
  },
  {
    "id": "emp-43",
    "name": "AJAY MALIK",
    "category": "Unskilled",
    "monthlySalary": 10680,
    "salaryPerDay": 356,
    "bonusPerDay": 54,
    "daysWorked": 30,
    "extraDays": 0,
    "basicPercent": 70,
    "pfOptIn": true,
    "esiOptIn": true,
    "advance": null,
    "otherDeduction": 0
  },
  {
    "id": "emp-44",
    "name": "CHANDAN MALIK",
    "category": "Unskilled",
    "monthlySalary": 10680,
    "salaryPerDay": 356,
    "bonusPerDay": 54,
    "daysWorked": 29,
    "extraDays": 0,
    "basicPercent": 70,
    "pfOptIn": true,
    "esiOptIn": true,
    "advance": null,
    "otherDeduction": 0
  },
  {
    "id": "emp-45",
    "name": "ALOK BAG",
    "category": "Unskilled",
    "monthlySalary": 10020,
    "salaryPerDay": 334,
    "bonusPerDay": 66,
    "daysWorked": 28,
    "extraDays": 0,
    "basicPercent": 70,
    "pfOptIn": true,
    "esiOptIn": true,
    "advance": null,
    "otherDeduction": 0
  },
  {
    "id": "emp-46",
    "name": "CHANDAN VERMA",
    "category": "Unskilled",
    "monthlySalary": 9750,
    "salaryPerDay": 325,
    "bonusPerDay": 75,
    "daysWorked": 25,
    "extraDays": 0,
    "basicPercent": 70,
    "pfOptIn": true,
    "esiOptIn": true,
    "advance": null,
    "otherDeduction": 0
  },
  {
    "id": "emp-47",
    "name": "SAGAR CHANDRA MAJHI",
    "category": "Skilled",
    "monthlySalary": 51000,
    "salaryPerDay": 1700,
    "bonusPerDay": 0,
    "daysWorked": 29,
    "extraDays": 0,
    "basicPercent": 70,
    "pfOptIn": false,
    "esiOptIn": false,
    "advance": null,
    "otherDeduction": 0
  },
  {
    "id": "emp-48",
    "name": "PUNIT SODHANI",
    "category": "Special",
    "monthlySalary": 60000,
    "salaryPerDay": 2000,
    "bonusPerDay": 0,
    "daysWorked": 30,
    "extraDays": 0,
    "basicPercent": 70,
    "pfOptIn": false,
    "esiOptIn": false,
    "advance": null,
    "otherDeduction": 15000
  },
  {
    "id": "emp-49",
    "name": "BIDYUT RAY",
    "category": "Skilled",
    "monthlySalary": 21700,
    "salaryPerDay": 533,
    "bonusPerDay": 257,
    "daysWorked": 30,
    "extraDays": 0,
    "basicPercent": 70,
    "pfOptIn": true,
    "esiOptIn": false,
    "advance": null,
    "otherDeduction": 0
  },
  {
    "id": "emp-50",
    "name": "Nitish Kumar",
    "category": "Unskilled",
    "monthlySalary": 9600,
    "salaryPerDay": 320,
    "bonusPerDay": 35,
    "daysWorked": 26,
    "extraDays": 0,
    "basicPercent": 70,
    "pfOptIn": true,
    "esiOptIn": true,
    "advance": null,
    "otherDeduction": 0
  },
  {
    "id": "emp-51",
    "name": "RAJASHREE KHAN",
    "category": "Skilled",
    "monthlySalary": 23000,
    "salaryPerDay": 733,
    "bonusPerDay": 33,
    "daysWorked": 10,
    "extraDays": 0,
    "basicPercent": 70,
    "pfOptIn": false,
    "esiOptIn": false,
    "advance": null,
    "otherDeduction": 0
  }
];
