export type EmployeeInput = {
  id: string;
  name: string;
  category: string;
  monthlySalary: number;
  salaryPerMonth?: number;
  salaryPerDay?: number;
  bonusPerDay?: number;
  daysWorked: number;
  extraDays: number;
  basicPercent?: number;
  pfOptIn?: boolean;
  esiOptIn?: boolean;
  advance?: number | null;
  otherDeduction: number;
  officialAttendance?: number;
  officialBonus?: number;
  specialBonus?: number | null;
  performanceBonus?: number | null;
};

export type SalaryRow = EmployeeInput & {
  perDayWage: number;
  salaryPerDay: number;
  bonusPerDay: number;
  dailyBonus: number;
  totalSalary: number;
  absentDays: number;
  absentDeduction: number;
  basicPercent: number;
  earnedSalary: number;
  basicSalary: number;
  hra: number;
  travelAllowance: number;
  performanceBonus: number;
  specialBonus: number;
  grossPayable: number;
  pfOptIn: boolean;
  esiOptIn: boolean;
  employeePf: number;
  employerPf: number;
  esi: number;
  employerEsi: number;
  professionalTax: number;
  netPayable: number;
  totalCost: number;
};
